### PR TITLE
Create weather app using async/await and fetch api

### PR DESCRIPTION
**Pull request by bolah2009**
### Integrate the open weather API

-  Use async/await and fetch API to get data from the weather API and populate data to the DOM

TODO: 

 - [x] Format unit appropriately, add `%`, `°F`, `°C`, `mph`, km/h`, etc
 - [x] Add unit conversions from metric to imperial and vice versa
 - [x] Style background to change according to weather conditions
 - [x] Improve city search using Google Places API to generate search suggestions
 - [x] Add current location functionality using geolocation API

Live Preview: Please use link generated by `netlify/bolah-js-weather/deploy-preview` below
To use on development environment, please, configure  [`dotenv`](https://github.com/motdotla/dotenv) using a `.env` file content of this format :point_down:

```env
WEATHER_API=<KEY>
```

The placeholder of the search input shows the format it accepts which is a city name `city`. e.g. `lagos`, `london`, `Abuja` and it's not case sensitive. See the demo below.

weather_app

#### Update: Weather Data is now properly formatted. 

weather_app2

### CODE REVIEW

**Review by JamesOkunlade — CHANGES_REQUESTED** [review]
### Hi @bolah2009 ✋ an error is preventing weather details from fetching, please check your console to see and fix this error. 

- You should do well to fix the stickler errors as well.

**Status: `Changes required`**

**James Okunlade**
**Happy coding!**

**Comment by bolah2009** [comment]
> Hi @bolah2009  an error is preventing weather details from fetching, please check your console to see and fix this error.

I don't have this error on my end, could you do point out the error and suggestion on how to solve it from your end? I am thinking it has to do with the weather API key. :thinking: 
Also, try testing with the [Netlify deploy preview](https://deploy-preview-3--bolah-js-weather.netlify.com/), environment variables including the weather API key is configured on Netlify.

> You should do well to fix the stickler errors as well.

Hey, @JamesOkunlade could you suggest ways to fix the stickler error?
I am thinking it has to do with the use of `async/await` and Stickler `linter` not been able to parse it. :thinking: 

Thanks for the review @JamesOkunlade :+1:

**Comment by JamesOkunlade** [comment]
It a `401` error. Apparently, you're not authorised to use the URL you're using.

image

- You could use this instead 

``` 
 const uri = `http://api.openweathermap.org/data/2.5/weather?q=${location}&APPID=${apiKey}
```

Also, make sure to update your README.md file with the format of City name to search.

**Comment by bolah2009** [comment]
Hi @JamesOkunlade , as I said earlier, this is because the weather API `KEY` is configured locally using [`dotenv`](https://github.com/motdotla/dotenv) and on production using Netlify environment variables. Please review using this link `https://deploy-preview-2--bolah-js-weather.netlify.com` which is the current deploy preview or set the API key locally using a `,env` file content of this format :point_down: .
```env
WEATHER_API=<KEY>
```

As shown in the demo below, there's no such error. 

> It a 401 error. Apparently, you're not authorised to use the URL you're using.

Could you answer this? :point_down: 

> Hey, @JamesOkunlade could you suggest ways to fix the stickler error?
I am thinking it has to do with the use of async/await and Stickler linter not been able to parse it. thinking

The placeholder shows the format it accepts which is a city name `city`. e.g. `lagos`, `london`, `Abuja` and it's not case sensitive. See the demo below.

> Also, make sure to update your README.md file with the format of City name to search.


weather_app

**Review by AdnanAfsari — APPROVED** [review]
Hello @bolah2009 ✋ 

Nice improvement 👏 .Looks good now.Its a 👍 from me.

Note: Do not forget to update your live app, I think its not updated yet 😄.

Happy Coding
Adnan Afsari

**Comment by bolah2009** [comment]
> Note: Do not forget to update your live app, I think its not updated yet 

Oh, thanks for the observation. 👍🏾

Thanks for the review @AdnanAfsari

**Pull request closed without merging**
